version: '3'
services: 
    app:
        container_name: 'ridehail'
        build: .
        depends_on: 
            - postgres
        ports: 
            - "8080:3000"
    postgres:
        image: postgres:12.1
        ports: 
            - "5432:5432"
        container_name: 'ridehail-db'
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: "${POSTGRES_DB}"