version: '3'
services: 
    redis:
        image: redis:5.0.7
    app:
        container_name: 'ridehail'
        build: .
        depends_on: 
            - postgres
            - redis
        ports: 
            - "3000:3000"
        environment:
            - REDIS_URL="${REDIS_URL}"
    postgres:
        image: postgres:12.1
        ports: 
            - "5432:5432"
        container_name: 'ridehail-db'
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: "${POSTGRES_DB}"
    worker:
        build: .
        container_name: my-worker
        environment:
            NODE_ENV: 'development'
            PORT: 3000
        depends_on:
            - postgres
            - redis