version: '3'
services: 
    redis:
        container_name: 'redis'
        image: redis:latest
        command: ["redis-server", "--bind", "redis", "--port", "6379"]
        ports: 
            - "6379:6379"
    app:
        container_name: 'ridehail'
        build: .
        depends_on: 
            - postgres
            - redis
        ports: 
            - "3000:3000"
        env_file:
            - ./.env
    postgres:
        image: postgres:12.1
        ports: 
            - "5432:5432"
        container_name: 'ridehail-db'
        env_file:
            - ./.env
    worker:
        build: .
        container_name: queue-manager
        command: "sh -c 'npm run worker'"
        env_file:
            - ./.env
        depends_on:
            - postgres
            - redis